### ISSUE TITLE
Error in Bin sequence

### ISSUE THREAD

**Issue by TehreemZainab** [ucrbioinfo/DeeplyEssential#2]
I am running your code with DEG data that you already shared in closed issue. Were these files exactly to be used?
Code is giving me this error.
python main.py essential non-essential orthoMCL.txt dataset.txt -c -c
2021-02-09 14:11:42.434757: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-02-09 14:11:42.434795: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
main.py:128: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  main()
Traceback (most recent call last):
  File "main.py", line 128, in <module>
    main()
  File "main.py", line 47, in main
    feat.getFeatures(paramDict['bins'])
  File "/home/seecs/DeeplyEssential-master/FeatureGeneration.py", line 179, in getFeatures
    binnedSequence = self.EssentialGeneSeqInfo[seqName][startPos:endPos]
TypeError: slice indices must be integers or None or have an __index__ method

**Comment by mdahasan** [comment]
I'm not sure what the error is. (Not actively working on it for years also isn't helping)
However, I believe this could be a dataset issue. The dataset currently available from DEG probably has updated and that could cause issues reading the data. I have added a link to the dataset that I originally used for the project. Please see the README section, you will find a google drive link to download the original dataset. 

Hope this helps.
